### ISSUE TITLE
Citations not working

### ISSUE THREAD

**Issue by albertovalzgris** [tompollard/phd_thesis_markdown#101]
Hi, first of all thank you for keeping this up. It's a wonderful tool.

I can't get my citations anymore. I guess this has to do with Pandoc moving from

```--filter pandoc-citeproc```

to simply

```--citeproc```

or at least this work in other makefiles I use. However I can't find this setting in this repo…

**Comment by dendrondal** [comment]
We actually migrated from `pandoc-citeproc` to `citeproc` about two weeks ago, so it may just be a matter of pulling in those changes.

**Comment by albertovalzgris** [comment]
Oh, thank you @dendrondal for your reply. I'd just like to ask which files contains this info, so that maybe I could avoid rebuilding my entire folder, which has customised sections of course… thank you.

**Comment by dendrondal** [comment]
The `Makefile` handles this, and you probably want to get the `install` script for your os to make sure all other libraries are up to date.

**Comment by albertovalzgris** [comment]
Restarted from scratch, thank you.
