### ISSUE TITLE
Fix: Short captions for figures and tables

### ISSUE THREAD

**Issue by prakaa** [tompollard/phd_thesis_markdown#116]
I am currently using this template as a building block (great work @tompollard!), but have gone with using the excellent [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) instead of `pandoc-xnos` (you need to change pandoc flags in the Makefile).

In theory, this should mean I should have been able to use short captions for both figures and tables using Lua filters for [figure short-captions](https://github.com/pandoc/lua-filters/tree/master/short-captions) and [table short-captions](https://github.com/pandoc/lua-filters/tree/master/table-short-captions). 

But if anyone else is like me and is trying to use with pandoc 3.0+, you'll notice `short-captions` (Lua filter for figures) doesn't work because pandoc Lua has been updated to use Figures from 3.0 onwards.

**Fix:**

- jpcirrus has written a very simple and concise fix here: https://github.com/jgm/pandoc/issues/7915#issuecomment-1427113349 
- `table-short-captions` still works.
- I have put both of these `.lua` files in a `filters` folder. These are called via a flag, e.g. `--lua-filter=filters/figure-short-captions.lua`
- I can confirm this works for me for both figures and tables for pandoc 3.1.2 - i.e. I can add short captions and they appear in the list of figures and list of tables

**Moving forward**
Note that this may be addressed within `pandoc` itself, there is an open PR that may resolve this: https://github.com/jgm/pandoc/pull/8617

I can prepare a PR for this change, but it will require moving from `pandoc-xnos` to `pandoc-crossref`. Alternatively, I am still refining my repo (which is heavily based on this one, but with some updates/opinionated changes), but happy to share with those interested and potentially release down the line.

**Comment by tompollard** [comment]
@prakaa thanks for raising this issue. I think switching to pandoc-crossref makes sense. Please could you open a PR?

**Comment by prakaa** [comment]
Thanks @tompollard, will fork this repo and create a PR.

I imagine this will require:

- [x] Changing `xnos` flags to `crossref` in Makefile
- [x] Adding working `figure-short-captions` and `table-short-captions` Lua filters, and calling these in Makefile
- [x] Changing referencing in the sample text to conform with `crossref` style
- [x] Updating README
  - [x] Require pandoc 3.1+

**Comment by tompollard** [comment]
thanks @prakaa, i appreciate you looking at this. sounds good to me!

**Comment by prakaa** [comment]
@tompollard  PR ready, please see #118
