### ISSUE TITLE
Example on .bib references

### ISSUE THREAD

**Issue by DeastinY** [tompollard/phd_thesis_markdown#16]
Hey,
this is probably just me, not knowing anything about bibtex, but I'd love some examples !
There is a @book{Cousteau1963} entry in the references.bib, but I can't figure out how to reference it.

**Comment by DeastinY** [comment]
Those are some of the errors --verbose shows when running pandoc

> 
Package hyperref Warning: Option `bookmarks' has already been used,
(hyperref)                setting the option has no effect on input line 61.

Package ctable Warning: 
(ctable)                Transparency disabled: pdfTeX is not running in PDF mod
e .

No file input.aux.

Package hyperref Warning: Rerun to get /PageLabels entry.


LaTeX Warning: Citation `test' on page 7 undefined on input line 283.

Package hyperref Warning: Difference (2) between bookmark levels is greater 
(hyperref)                than one, level fixed on input line 613.

LaTeX Warning: There were undefined references.

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

Package hyperref Warning: Option `bookmarks' has already been used,
(hyperref)                setting the option has no effect on input line 61.
Package ctable Warning: 

(ctable)                Transparency disabled: pdfTeX is not running in PDF mod
e .

LaTeX Warning: Citation `test' on page 9 undefined on input line 283.

**Comment by tompollard** [comment]
Hi Richard, the first part of the metadata ('Cousteau1963') is the key that you use for your citation. 

Just add [@Cousteau1963] to the text where you want the citation to appear. e.g., see:
https://raw.githubusercontent.com/tompollard/phd_thesis_markdown/master/source/08_introduction.md

The easiest way to create the bib file is to export your references from a reference manager like Zotero, Mendeley, etc.

Hope this helps! I'll look into the errors when I get a chance.

**Comment by DeastinY** [comment]
Thanks for the fast response !
I tried \cite{Cousteau1963}, but I'll come back to you, with feedback, tomorrow :)!

**Comment by tompollard** [comment]
You should use the syntax in the example above - [@Cousteau1963] not \cite{Cousteau1963}

**Comment by DeastinY** [comment]
Works perfecty fine.
Sorry for overlooking the example :smile:
