### ISSUE TITLE
Reduce font size of bibliography

### ISSUE THREAD

**Issue by Nowosad** [tompollard/phd_thesis_markdown#18]
Is it possible to reduce font size of bibliography? I've tried to do it by adding "\renewcommand*{\bibfont}{\footnotesize}" into preamble.tex, but afterwards it is not possible to comple pdf.

**Comment by Nowosad** [comment]
The only working solution that I found is to add \footnotesize before References chapter.

**Comment by tompollard** [comment]
Thanks @Nowosad and glad to hear you found a solution. I'll look at this when I get a chance to see if I can find a cleaner approach. Pull requests welcome in the meantime!
