### ISSUE TITLE
Roman numbering in {.unnumbered} sections

### ISSUE THREAD

**Issue by desiguel** [tompollard/phd_thesis_markdown#19]
Not an issue per-se, more of a query about functionality...

Is it possible to use roman numbering in the {.unnumbered} sections and then re-start arabic numbering in the normal chapters?

In template.tex I tried including:

\pagenumbering{roman} after \begin{document}

then:

\pagenumbering{arabic} before $body$

but all this does is give me arabic page numbers throughout the whole document.

I then tried including sections for \mainmatter and \frontmatter in template.tex with the different numbering styles but this didn't work either.

No probs if you don't have time to respond, but if you have any ideas about where I'm going wrong that would help me out a lot!

**Comment by desiguel** [comment]
Hacked it :)

I included \pagenumbering{roman} up the top of the title page then in the page before content I included \newpage \pagenumbering{arabic} at the bottom.

**Comment by tompollard** [comment]
Thanks @desiguel, glad to hear you found a solution! Am I okay to close this issue now or do you think it would be helpful to make a change to the template files?

**Comment by desiguel** [comment]
Just close it now I think. I'm not sure that adding my changes to the template files is a good idea as they change document formatting past the point of insertion potentially creating confusion for the user if they change page order or add/delete files.

**Comment by tompollard** [comment]
thanks @desiguel, will do.
