### ISSUE TITLE
Power -1

### ISSUE THREAD

**Issue by JPFrancoia** [tompollard/phd_thesis_markdown#21]
Hi,

Great tool. I'm using it to write my PhD thesis as well.

I noticed a problem however:

```
9 mL.min^-1^
```

Does not render well. The minus symbol does not seem to be in the subscript when rendering to pdf, with the xelatex engine. It does render correctly in html though. Do you have the same behaviour ?

EDIT:

My bad, it does that if I try to change the font:

```
\usepackage{fontspec}
\setmainfont{Calibri}
```

**Comment by Nowosad** [comment]
I have the same problem. Is it possible to have proper size subscript without changing the font?

**Comment by Nowosad** [comment]
I've changed of ` \DeclareMathSizes` to `\DeclareMathSizes{12}{13}{7}{7}` and now I have a proper sized subscript. Maybe that's the solution.

**Comment by tompollard** [comment]
Many thanks for picking this up. I have updated DeclareMathSizes as suggested by @Nowosad.
