### ISSUE TITLE
Syntax highlighting 

### ISSUE THREAD

**Issue by httpete-ire** [tompollard/phd_thesis_markdown#23]
More a question then an issue but is it possible to apply syntax highlighting to a code block? Also can you set a figure on the code block?

Thanks

**Comment by tompollard** [comment]
It is possible to add syntax highlighting to a code block using the method below:

\`\`\`python
CODE HERE
\`\`\`

...which will output something like:

```python
mood = 'happy'
if mood == 'happy':
    print("I am a happy robot")
```

I have added an example to the following section: 
https://github.com/tompollard/phd_thesis_markdown/blob/master/source/10_chapter_1.md

**Comment by tompollard** [comment]
> Also can you set a figure on the code block?

I'm not sure if I understand this bit of the question. You would like a figure to appear inside the code block?

**Comment by httpete-ire** [comment]
@tompollard I didnt know it accepted code braces, just thought it was code blocks (tab indentation). Is it possible to set the theme of the syntax highlighting to a dark theme. 

What I meant is that the actual code block itself is figured so I can reference it else where

**Comment by tompollard** [comment]
> Is it possible to set the theme of the syntax highlighting to a dark theme. 

Syntax highlighting style can be defined in Pandoc with the ```--highlight-style=STYLE``` argument. For more detail, see: http://pandoc.org/README.html#syntax-highlighting

I have added the highlight-style argument to the Makefile with the default style: https://github.com/tompollard/phd_thesis_markdown/blob/master/Makefile. Replacing pygments with espresso should give you a dark block.

**Comment by tompollard** [comment]
It looks like you may be able reference the code block by adding an attribute to the block using the method described at: http://pandoc.org/README.html#verbatim-code-blocks

~~~
    ```#coderef .python
    CODE HERE
    ```
~~~
