### ISSUE TITLE
Header capitalised 

### ISSUE THREAD

**Issue by httpete-ire** [tompollard/phd_thesis_markdown#24]
Hi, I just noticed that when `h3` headers are output they are capitalise by default, where can I change this. Thanks

```
# Introduction
## Introduction
### Introduction
#### Introduction
##### Introduction
###### Introduction
```

Outputs this 

<img width="625" alt="screen shot 2016-03-27 at 15 08 52" src="https://cloud.githubusercontent.com/assets/1556430/14065751/4ac17f88-f42e-11e5-8c3e-96e508b5fe9f.png">

**Comment by tompollard** [comment]
You should be able to change header styles in the [Latex style file](https://github.com/tompollard/phd_thesis_markdown/blob/master/style/preamble.tex). Look for this chunk:

```
% HEADINGS
\usepackage{sectsty}
\usepackage[normalem]{ulem}
\sectionfont{\rmfamily\mdseries\Large}
\subsectionfont{\rmfamily\mdseries\scshape\large}
\subsubsectionfont{\rmfamily\bfseries\upshape\large}
```
