### ISSUE TITLE
Change Margins

### ISSUE THREAD

**Issue by DeastinY** [tompollard/phd_thesis_markdown#25]
Hi Tom,
I tried a bunch of things to change the margin on the page, but nothing seems to work. Any headsup on how I can accomplish a little less white on the sides ?
Regards,
Richard

**Comment by Nowosad** [comment]
Hi @DeastinY ,
You can use a geometry package:
`\usepackage[top=2.5cm,bottom=2.5cm,left=3.5cm,right=1.5cm]{geometry}`

**Comment by DeastinY** [comment]
Hi @Nowosad, thanks for reaching out !
When using the geometry package I get :

```
! LaTeX Error: Option clash for package geometry.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.194 \setlength
                {\parskip}{9pt}
No pages of output.
Transcript written on /tmp/tex2pdf.17265/input.log.

Makefile:28: recipe for target 'pdf' failed
make: *** [pdf] Error 43
```

**Comment by Nowosad** [comment]
Are you sure, that you don't have a second line with geometry package somewhere in the preamble.tex? Your problem looks similar to this one - http://tex.stackexchange.com/a/226218/45350 .

**Comment by DeastinY** [comment]
Great ! That's it :+1: 
I was scouting through the template.tex, but did not check in the preamble.
Thanks a bunch !

**Comment by tompollard** [comment]
Thanks for helping out with this @Nowosad
