### ISSUE TITLE
Chapters, tables and figures

### ISSUE THREAD

**Issue by fgardos** [tompollard/phd_thesis_markdown#26]
Hello Tom, 
thanks to share your work about your phd_thesis_markdown. 

I am adapting your template for my thesis in Spanish and I would like to ask how is possible to change titles like "Chapter", "Table", "Figure" for other similar works but in Spanish ;)

Any clue will be welcome!
Thanks again, 
Paco

**Comment by DeastinY** [comment]
Hey @fgardos,
I'm not completely certain, but try adding -V lang=spa to the commands in the Makefile.
If I remember correctly that's what I did to get it to work in German :)

**Comment by fgardos** [comment]
Thanks DeastinY ;)

**Comment by tompollard** [comment]
Thanks @DeastinY. Good luck @fgardos and let us know if you have any more questions. Look forward to hearing how things go!

**Comment by tobiasbueschel** [comment]
@fgardos have you had any luck with changing the language through the `Makefile`? If yes, we can probably add this to the `readme` and subsequently close this issue :)

**Comment by TimonVS** [comment]
I added `-V lang=nl` as suggested here, but it doesn't seem to change anything at all.

```make
pdf:
	pandoc "$(INPUTDIR)"/*.md \
	-o "$(OUTPUTDIR)/thesis.pdf" \
	-H "$(STYLEDIR)/preamble.tex" \
	--template="$(STYLEDIR)/template.tex" \
	--bibliography="$(BIBFILE)" 2>pandoc.log \
	--csl="$(STYLEDIR)/ref_format.csl" \
	--highlight-style pygments \
	-V fontsize=12pt \
	-V papersize=a4paper \
	-V documentclass:report \
	-V lang=nl \
	-N \
	--latex-engine=xelatex \
	--verbose
```

Removing the template and header option and adding `--chapters` does work however ("Chapter 1" is correctly translated to "Hoofdstuk 1"), but that is obviously not the whole solution because then I can't use the provided template anymore.

**Comment by TimonVS** [comment]
I found out where it goes wrong:

`style/template.tex:146`
```make
$if(lang)$
\ifxetex
  \usepackage{polyglossia}
  \setmainlanguage{$mainlang$}
\else
  \usepackage[$lang$]{babel}
\fi
$endif$
```

It works completely fine when I replace this with: `\usepackage[$lang$]{babel}`.

I also had to change `-V lang=nl` to `-V lang=dutch`.

**Comment by jarquinsandra** [comment]
Thanks for the solution TimonVS, it worked great for me with spanish
