### ISSUE TITLE
Archive repo in Figshare

### ISSUE THREAD

**Issue by tompollard** [tompollard/phd_thesis_markdown#27]
I'm thinking about archiving a copy of this repo in [Figshare](https://figshare.com/).  For more detail see: https://figshare.com/blog/Working_with_Github_and_Mozilla_to_enable_Code_as_a_Research_Output_/117

To everyone who has contributed, please let me know if you would like to be listed on the Figshare project and, if so, what name you would like to be displayed. 

(@therealmarv, @davidsan, @ArcoMul, @wcaleb, @Nowosad, @matthewgthomas, @dennisweissmann, @DeastinY) 

Thanks!
Tom

**Comment by dennisweissmann** [comment]
I have no problem with it :)

Even though I technically contributed you don't have to mention me (I just updated the readme), but if you want to, feel free to do so :) My full name is on my GitHub page.

Cheers,

Dennis

**Comment by davidsan** [comment]
Same here. :+1:

**Comment by DeastinY** [comment]
In general same here.
I did not know about Figshare until now - can anyone elaborate where they get their money from ? Doesn't seem to be OpenSource, but commercial. Just out of interest, the idea itself is great :smile:

**Comment by tompollard** [comment]
My understanding is that Figshare gets money from offering a premium options to users (e.g. offering extra space on their servers) and also through partnering with article publishers to host and render data. It's a nice service...worth checking out. A popular alternative is [Zenodo](http://zenodo.org/).

**Comment by therealmarv** [comment]
No problem with Figshare but always keep your repo here on github ;)

My Name: Marvin Reimer

I've written successfully my Diploma thesis in German with your template and modified it on language settings etc. . Will look soon if there is something more contributable to your original template (probably in the README).

**Comment by ArcoMul** [comment]
Fine by me :+1:, my name is, unsurprisingly: Arco Mul :wink:

**Comment by Nowosad** [comment]
Nice!
My name is Jakub Nowosad.

**Comment by tompollard** [comment]
I didn't have any luck with the Figshare instructions [here](https://mozillascience.github.io/code-research-object/) and [here](https://figshare.com/blog/Working_with_Github_and_Mozilla_to_enable_Code_as_a_Research_Output_/117), so ended up submitting the code to [Zenodo](https://zenodo.org/) instead.

The author list was automatically generated from the commit log. Let me know if there are any issues with the list and I'll try to update it manually. 

The citation is: 

> Tom Pollard et al.. (2016). Template for writing a PhD thesis in Markdown. Zenodo. 10.5281/zenodo.58490

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.58490.svg)](http://dx.doi.org/10.5281/zenodo.58490)
