### ISSUE TITLE
How do I ignore specific page in Table of Contents ?

### ISSUE THREAD

**Issue by ckybonist** [tompollard/phd_thesis_markdown#32]
In latex I can use `\thispagestyle{empty}` below the page content, then latex will know don't put this page in table of contents, even skip the page numbering.

However, I use this command in markdown, It only hide the page number.

Any instructions ?

**Comment by DeastinY** [comment]
Not sure, but maybe try it with a double backslash ?

**Comment by ckybonist** [comment]
The double backslash means newline in Latex, isn't it ?

**Comment by DeastinY** [comment]
My impression was, that sometimes the slash get's lost in markdown, so I was hoping that a single slash would be passed to Latex :) Did you try it out yet ? Could still be completely wrong though

**Comment by ckybonist** [comment]
Well... It explicitly showed `\thispagestyle{empty}` on pdf if I use double backslash, like this:


![2016-08-24 17 24 01](https://cloud.githubusercontent.com/assets/3832925/17925474/b4cc3802-6a1f-11e6-894c-4e4815a1981c.png)


By the way, I think single backslash is valid, as the list of table (the image above) was generated by
`\listoftable`.

**Comment by tobiasbueschel** [comment]
@ckybonist you can use:
```
\pagenumbering{gobble}
```
 to switch off page numbering.

If you like to activate it again you can use:
```
\pagenumbering{roman}
\setcounter{page}{1}
```

Hereby, you can replace roman with alph to trigger arabic numerals as well.  Using `\setcounter{page}{1}` you can select the page number that the new section should start from.

If you switch back and forth between numeral formats the following might be useful so that LaTeX doesn't complain:
```
\newpage
\setcounter{page}{1}
\renewcommand{\thepage}{\arabic{page}}
```

**Comment by ckybonist** [comment]
`\pagenumbering{gobble}` works.... Although this command ignore numbering the page, it still put the title of page into table of contents.

![2016-09-14 8 01 13](https://cloud.githubusercontent.com/assets/3832925/18495539/713ad7aa-7a51-11e6-8819-c2e6b212bfec.png)
