### ISSUE TITLE
Table with numeric values aligned to right

### ISSUE THREAD

**Issue by lf-araujo** [tompollard/phd_thesis_markdown#37]
Hi Tom,

Great package you put together here. Thanks. I have a question though, I've read throughout the code and I couldn't quite understand how are you  rendering tables. It seems the main culprit is the threeparttable package, but there aren't instructions on how to design these in markdown. Sure, there is one example, but I can't make it align the numeric columns to right. Is it possible? Could you shed some light on how you are rendering the tables?

Best,

**Comment by tobiasbueschel** [comment]
I would be curious to know this as well @lf-araujo @tompollard :)

Btw, the template also works with pure LaTeX tables, so you can use the following generator for tables as well: http://www.tablesgenerator.com/

**Comment by lf-araujo** [comment]
Hi @tobiasbueschel , after looking at the pandoc documentation I found the answer... Pandoc renders the table directly. Secondly, there are several ways to align the table to right or left, the one that I found more easy is the pipes table format. Have a look at pandoc.org/manual.html.

**Comment by tobiasbueschel** [comment]
ah nice! Thanks @lf-araujo

**Comment by tobiasbueschel** [comment]
@tompollard we can probably close this issue :)

**Comment by tompollard** [comment]
thanks @tobiasbueschel and @lf-araujo...closing!
