### ISSUE TITLE
Labels in figures missing in Latex output

### ISSUE THREAD

**Issue by BonarBeavis** [tompollard/phd_thesis_markdown#48]
As said, the labels get stripped and it is not possible to reference a figure. See the output [PDF](https://github.com/tompollard/phd_thesis_markdown/blob/master/output/thesis.pdf).

**Comment by jeiros** [comment]
Also seeing this. Any idea on how to fix it?

**Comment by tompollard** [comment]
@BonarBeavis @jeiros I see it, but I haven't had a chance to look into it yet - sorry. I wondered whether it had anything to do with the most recently merged pull request https://github.com/tompollard/phd_thesis_markdown/pull/47

**Comment by tompollard** [comment]
If you have time, please could you post a snippet of the expected output vs current output?

**Comment by jeiros** [comment]
This is the problem:

<img width="624" alt="screen shot 2017-02-15 at 16 14 14" src="https://cloud.githubusercontent.com/assets/10696140/22983378/ddf6790a-f399-11e6-9994-829cdb747a68.png">

Don't really know how to fix this, as I just discovered pandoc yesterday and I am exploring it to write my PhD thesis in the future. Thanks for putting this repo up, before finding it I couldn't really get much to work 😄

**Comment by tompollard** [comment]
Could you try `git checkout 52483eddcffb63fee479c5b34e43ed80382e1254` to roll back to the previous commit and see if this fixes the problem? If so, I'll rollback the most recent change.

**Comment by tompollard** [comment]
Doesn't seem to fix it. I'll take a look into this later today!

**Comment by tompollard** [comment]
Yep, it seems to be a problem with the pandoc-shortcaption updates. I'll revert these shortly, until we work out what's going on.

**Comment by tompollard** [comment]
I have reverted @martisak's pandoc-shortcaption update (https://github.com/tompollard/phd_thesis_markdown/pull/47), which fixes this issue but unfortunately means that we'll need to manually generate the list of figures page again for now.

**Comment by BonarBeavis** [comment]
With the following syntax the shortcaptions and references work:
```
![Long caption with LaTeX](img.png "alt image caption"){#fig:mylabel}
```

**Comment by Tamriel** [comment]
It does not work for the html output neither: https://github.com/tompollard/phd_thesis_markdown/blob/master/output/thesis.html#L328

**Comment by jeiros** [comment]
@BonarBeavis with @tompollard reverting the pandoc-shortcaption update your suggested syntax is still printing out the full label in the Table of Figures for me if I use `\listoftables`.

Also, to reference the figure in the text with your syntax, should `\ref{mylabel}` be used? If so, I am back to getting `Figure ??` in the pdf output.

**Comment by jeiros** [comment]
Nevermind, it's `\ref{fig:mylabel}`. Still seeing the long captions in the List of Figures though.

**Comment by BonarBeavis** [comment]
@jeiros the mentioned syntax works with the update.
