### ISSUE TITLE
Error 43 even after running installation script

### ISSUE THREAD

**Issue by j0ma** [tompollard/phd_thesis_markdown#50]
Hi there,

I cloned the repo and went through the instructions, yet when I run:

```
pandoc "/Users/admin/Documents/school/thesis/markdown_thesis/source"/*.md \
	-o "/Users/admin/Documents/school/thesis/markdown_thesis/output/thesis.pdf" \
	-H "/Users/admin/Documents/school/thesis/markdown_thesis/style/preamble.tex" \
	--template="/Users/admin/Documents/school/thesis/markdown_thesis/style/template.tex" \
	--bibliography="/Users/admin/Documents/school/thesis/markdown_thesis/source/references.bib" 2>pandoc.log \
	--csl="/Users/admin/Documents/school/thesis/markdown_thesis/style/ref_format.csl" \
	--highlight-style pygments \
	-V fontsize=12pt \
	-V papersize=a4paper \
	-V documentclass:report \
	-N \
	--latex-engine=xelatex
```

I still get 

```make: *** [pdf] Error 43```

I tried to run `sudo tlmgr update` on the dependencies, but that didn't do the trick either. What is weird, however, is that I **am** able to create pdf's with `pandoc -o foo.pdf bar.md`. Other output formats like html work fine.

Any idea what could be the issue? Thanks!

**Comment by mlbernauer** [comment]
@j0ma 

Check `pandoc.log` which is created in the directory where you run `make pdf`....when I got this error my log contained the following

```
! LaTeX Error: File `siunitx.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.134 ^^M

pandoc: Error producing PDF
```
Which was fixed after running  `sudo apt-get install texlive-science`

**Comment by Nowosad** [comment]
@tompollard Close?

**Comment by tompollard** [comment]
@Nowosad yep, thanks! (& btw I've just added you as a collaborator on the repo).
