### ISSUE TITLE
Why not using pandoc-crossref?

### ISSUE THREAD

**Issue by sbacelar** [tompollard/phd_thesis_markdown#53]
To cross-reference figures, display equations, tables and sections.

**Comment by tompollard** [comment]
I'm not familiar with pandoc-crossref. Please could you explain a little more about how it will help?

**Comment by sbacelar** [comment]
It's a very useful pandoc filter. You can read all the information about it in [https://github.com/lierdakil/pandoc-crossref](https://github.com/lierdakil/pandoc-crossref)

**Comment by FlxVctr** [comment]
@sbacelar I had a look at it considering whether I could need it for my thesis, but don't really get the benefits to just referencing via Latex-commands. Am I missing something?

**Comment by Fankbai** [comment]
https://github.com/Fankbai/Science.md
@sbacelar

**Comment by JamesOwers** [comment]
> @sbacelar I had a look at it considering whether I could need it for my thesis, but don't really get the benefits to just referencing via Latex-commands. Am I missing something?

If you're only interested in generating pdf, then no. If you want to generate `thesis.html`, none of the \latex you put in the `*.md` files will render.

At the moment, I don't think we can reference listings and other stuff like that. So pandoc-crossref may be a good option to look into in future to minimise dependencies. I'll have a look if I get time.

**Comment by JamesOwers** [comment]
Ah, and, unless I'm missing something, I think we can't refer to sections by number just now, other than using \ref{name-of-header} (which only works when rendering pdf), or using `[manually written header name](#name-of-header)`. So this may be the reason to switch to `pandoc-crossref` http://lierdakil.github.io/pandoc-crossref/#section-labels.

I've fixed the travis build in #100, so this should be easy to test.
