### ISSUE TITLE
PDF ISSUE: Japanese characters (fonts)

### ISSUE THREAD

**Issue by Ragamuffin-Asa** [tompollard/phd_thesis_markdown#56]
I am truly not technical, but I have taken the challenge to write my (Bachelor) thesis in markdown by using this template and found this work-flow so pleasant I do not want to go back to Word. 

For my study I need to have Japanese characters incorporated into the thesis and this is where problems arose. My thesis is fully written, however in the generated pdf all the Japanese characters are missing. I presumed it had something to do with the font. I tried changing the font to MS Mincho in the _template.tex_ but when that didn't work I tried changing it in the _preamble.tex_ via this:
`Fonts and typesetting   `
`\setmainfont[Scale=1.1]{MS Mincho}`

Like I said, I am a true beginner at this stuff so I am sure I must be doing something wrong. Hopefully there is someone who can help me with this issue. I'll be much obliged.

What I basically need to know is:
**how to get Japanese characters into the thesis (pdf file)?** 

p.s. if I generate to .html or .docx the Japanese characters do appear.

**Comment by tompollard** [comment]
@Ragamuffin-Asa glad to hear you've enjoyed using the template. Adding the following two lines below `% FONTS` in the preamble.tex file should allow you to render the Japanese characters.

```
\usepackage{xeCJK}
\setCJKmainfont{YuMincho Medium}
```
e.g.:

<img width="432" alt="screen shot 2017-05-04 at 09 15 17" src="https://cloud.githubusercontent.com/assets/822601/25705199/82e1b0a4-30aa-11e7-85c5-d7c4754e7ce3.png">

**Comment by Ragamuffin-Asa** [comment]
Ahh! Thank you so much! 
Initially it didn't work, but after a re-installation of MacTeX 2016 it finally worked. (so I suppose there must have been an error in the installation) I do not have enough words to express my gratitude. 

And yes, I have never figured myself to use anything else but Word. However writing in Markdown (with the help of your template) makes writing so much more fun and easy. Now that the Japanese character issue is solved, I will definitely recommend this writing method to my fellow students.
