### ISSUE TITLE
Figure location in output pdf

### ISSUE THREAD

**Issue by miguelarbesu** [tompollard/phd_thesis_markdown#58]
Hi there,
First of all, thanks for uploading the template, I am using it to write my thesis and I love it!
I have found an issue with figure location in the pdf output. It seems that location is not consistent, depending on the size and space available in the output page. 
If I reduce the image size enough for the image to fit by fiddling with ```{ widht=xx% }```, then the image will be displayed at the bottom of the current page. Otherwise, it is plotted at the end of the chapter. 
The desired output here would be the image to be displayed in-place between paragraphs, or am I missing something?
Thanks!

**Comment by Nowosad** [comment]
Hi @miguelarbesu - you can specify the figure position using latex commands - take a look at https://www.sharelatex.com/learn/Positioning_images_and_tables

**Comment by miguelarbesu** [comment]
Thank you for the hint @Nowosad , I am absolutely new to latex.
I finally changed the ```\origfigure[b] ``` flag to  ```[h]``` in the template.tex file to force the positioning.

**Comment by tompollard** [comment]
Many thanks @Nowosad. @miguelarbesu, it sounds like this was solved, so I'll close the issue!
