### ISSUE TITLE
Error 43 persists!

### ISSUE THREAD

**Issue by arnaudmiribel** [tompollard/phd_thesis_markdown#59]
Hi there,

Great project! 
I have problems running the `make pdf` (error 43) although I installed the requirements from the `README.md`. It actually worked directly without having to run these requirements but since I did them, error 43 appears... (only updates changed something). When looking at the logs : 

`$ cat pandoc.log`

```
! Forbidden control sequence found while scanning use of \__cs_generate_from_si
gnature:nnNNNn.
<inserted text> 
                \par 
l.1767       \int_case:nnn

pandoc: Error producing PDF
```

Any idea on this ?

**Comment by Nowosad** [comment]
Do you have `xetex` installed?

**Comment by arnaudmiribel** [comment]
That was quick!
Doesn't seem familiar to me no... Should I ? 
I edit using Atom.

**Comment by tompollard** [comment]
hi @arnaudmiribel the makefile specifies "```--latex-engine=xelatex```", so you will need to make sure that you have `xetex` installed.

**Comment by arnaudmiribel** [comment]
Hi @tompollard , thanks for the help.
I did now download xelatex. Typing `xelatex` yields

``` 
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
```

But I still have the Error 43 when making `pdf`

**Comment by arnaudmiribel** [comment]
Ok don't know what was the problem (nor solution), but I removed all, cloned again, made sure `xelatex` was installed and ran the few command lines as indicated in the README.md 
Now it works!

**Comment by t-power89** [comment]
I keep getting this error and i do not know what is going on

**Comment by t-power89** [comment]
ok thans for the record this is the final bit of the output on bash

(/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))))
Runaway argument?
{\dim_set:Nn ##1{\fontdimen ##2##3}\dim_compare:nNnT ##1={0pt}{\settoheight \ET
C.
! Forbidden control sequence found while scanning use of \__cs_generate_from_si
gnature:nnNNNn.
<inserted text>
                \par
l.1767       \int_case:nnn
                           #2
No pages of output.
Transcript written on /private/var/folders/1g/23z7lh6s7yv2vhc6qwndr1nr0000gn/T/
tex2pdf.64683/input.log.
