### ISSUE TITLE
Figure position

### ISSUE THREAD

**Issue by arnaudmiribel** [tompollard/phd_thesis_markdown#60]
Hi there,

Is it possible to force the figure to be exactly where we code it should be for the `latex pdf` export? Rather than putting all of them in the end of the chapter ? For me, seems like figures appear at the right spot only for the `.html` export :)

Thanks a lot,

**Comment by Nowosad** [comment]
@arnaudmiribel  maybe this will help - https://github.com/tompollard/phd_thesis_markdown/issues/58

**Comment by arnaudmiribel** [comment]
Thank you very much @Nowosad that's exactly what I was looking for ! Sorry, I searched before but didn't find that thread.

**Comment by Nowosad** [comment]
No problem, I'm glad I could help.
