### ISSUE TITLE
Question: Why are two spaces needed after paragraphs?

### ISSUE THREAD

**Issue by therealmarv** [tompollard/phd_thesis_markdown#7]
I really like this template and will also use it for my diploma thesis.

Only one thing is questionable for me: Why are two spaces also needed after every paragraph even when I have a blank new line in between of two paragraphs?

It seems a littlebit extra work and most/all of the markdown I've seen do not need a both of them: Double spacing AND empty new line.

I will maybe fix that for me but I have not looked too deep into the templates and outputs (the pdf output seems to have an extra indention when two spaces are missing).

**Comment by tompollard** [comment]
thanks @therealmarv. i'll look at this as soon as I have a chance. The short answer is that the templates could do with a lot of cleaning up, so you are probably right...the extra spaces may well be unnecessary!
