### ISSUE TITLE
Change the default code highlighting ?

### ISSUE THREAD

**Issue by FrancescoFilippi** [tompollard/phd_thesis_markdown#70]
Is it possible to change the default code highlighting and use, let's say, something like the github markdown (light grey box included)?
E.g.
```javascript
mood = 'happy'
if mood == 'happy':
    print("I am a happy robot")
```

**Comment by tompollard** [comment]
I think this may have been implemented by @tobiasbueschel in https://github.com/tompollard/phd_thesis_markdown/pull/36

The pull request has been sitting around for an embarrassingly long time, so I'll take a look in the next day or two.

**Comment by tompollard** [comment]
@FrancescoFilippi see page 6 of: https://github.com/tompollard/phd_thesis_markdown/blob/master/output/thesis.pdf

Thanks go to @tobiasbueschel for this 

(Tobias, I didn't directly merge because git complained: "Patch is empty. Was it split wrong?", so sorry the commits aren't in your name. )

**Comment by FrancescoFilippi** [comment]
Looks really good! 
I'll definitely try to add another custom language syntax highlighting. Maybe open a pull request if I'll succeed.
