### ISSUE TITLE
Newbe to Latex and Pandoc

### ISSUE THREAD

**Issue by admin-teametry** [tompollard/phd_thesis_markdown#75]
I played around with the template.tex file and want to change the font for the PDF Output, but setmainfont and some other test always failed with Error 43.

Is there a simple solution changing the font, i.e. to Proxima Nova or Noto serif?

Andreas

**Comment by admin-teametry** [comment]
HI,

solved it bymyself. Thank you all for sharing this very good template. Makes my life as a social and psychological researcher much easier :-)

Andreas

**Comment by Nowosad** [comment]
Can you post your solution here? Maybe this is going to help somebody else in the future.

**Comment by admin-teametry** [comment]
Sure, actually I use this

`
%\usepackage{$fontfamily$}
\usepackage[T1]{fontenc}
\usepackage{lmodern}      

\usepackage[no-math]{fontspec}    
\defaultfontfeatures{Mapping=tex-text}  % This seems to be important for mapping glyphs properly

\setmainfont{Proxima Nova}
\setsansfont{Proxima Soft}`

**Comment by Nowosad** [comment]
Thanks!
