### ISSUE TITLE
[pdf] - change "Chapter" to "Kapitel" (de-DE)

### ISSUE THREAD

**Issue by pBergerD** [tompollard/phd_thesis_markdown#79]
I want to use this great template for German PDF.
If I call "make pdf", then the generated PDF will show "Chapter 1" or "Chapter 2" and so on.

How can I change "Chapter" to "Kapitel" (de-DE) for Header (#)?

I can not find a solution here. Thank you in advance for your feedback!

**Comment by artberg** [comment]
First try to add the following parameter in your _Makefile_ under the pdf section

`-V lang=de-DE \`

If the above snippet does not work, just add the the following line in _style/preamble.tex_

`\renewcommand{\chaptername}{Kapitel}`

But there are a few other changes  you need to make e.g.

`\renewcommand{\contentsname}{Inhaltsverzeichnis}`
`\renewcommand{\figurename}{Abb.}`
`\renewcommand{\tablename}{Tab.}`

or

`\renewcommand{\lstlistingname}{Code}`
`\renewcommand{\lstlistlistingname}{Codeverzeichnis}`

**Comment by pBergerD** [comment]
It works! Great help! Thank you!
