### ISSUE TITLE
Use .Rmd files instead of .md

### ISSUE THREAD

**Issue by jvcasillas** [tompollard/phd_thesis_markdown#9]
Hello, I was wondering if it was possible to use .Rmd files (to include R code) instead of .md. I figured I would ask before trying to do it on my own in case you had any insight that might save me time. Thanks in advance.

**Comment by tompollard** [comment]
Hmm...I'm not sure, but I'll look into it!

**Comment by jvcasill** [comment]
@tompollard I spent most of the afternoon playing with it and I was able to do it fairly easily. I had to start from scratch however. I will link it below, as it may be useful to you if you ever decide to implement this in your repository. 

https://github.com/jvcasill/ua_thesis_rmd

**Comment by gimrlima** [comment]
Hello! I'm also interested in adapting the template to .rmd. @tompollard What were your thoughts on @jvcasill's suggestion?  @jvcasill , you didn't use the template as detailed as this one? Any particular reasons?

**Comment by jvcasill** [comment]
@gimrlima I just made the changes necessary to 1) make it work and 2) adhere to the formatting requirements for my department. Other than that, nothing in particular. It wasn't too difficult and it has been quite useful.

**Comment by tompollard** [comment]
This is great, thanks guys. I'm keen incorporate the changes, but it will take a little time because I'm not familiar with .rmd, so will need to do some reading. Pull requests welcome in the meantime!

**Comment by TomHardwicke** [comment]
Hi - is there any news on this? I'm really keen to use your template Tom (I'm about to write my UCL thesis) but I would like to incorporate R code too to make the entire thesis reproducible. I'm not sure I have the technical expertise to assist with this myself but I will happily take a look if someone could point me in the right direction.
Thanks!

**Comment by jvcasill** [comment]
@TomHardwicke I would suggest you take a look at my repository. Download it and try it with your thesis class. It should work fine.

**Comment by tompollard** [comment]
Sorry @TomHardwicke, I haven't had time to look into this yet, but you've put it back on my radar!

**Comment by Nowosad** [comment]
@TomHardwicke there is quite easy solution - you can convert your .Rmd files to .md files and afterwards use template from this repository. To create .md file from .Rmd file, you could add a line into YAML part of the file (http://stackoverflow.com/questions/31914161/how-to-convert-rmd-into-md-in-r-studio) or convert file in R:

```
library('rmarkdown')
render("input.Rmd", "md_document")
```
